apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: twtfirst
    tier: database
  ports:
  - protocol: "TCP"
    port: 3306
    targetPort: 3306
  clusterIP: None
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-mysql
  labels:
    app: twtfirst
    tier: database
spec:
  selector:
    matchLabels:
      app: twtfirst
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: twtfirst
        tier: database
    spec:
      containers:
      - image: mariodsasir/proyecto:mysql
        name: db-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-pass
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-db
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc