apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: twtfirst
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: twtfirst
    tier: frontend
spec:
  selector:
    matchLabels:
      app: twtfirst
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: twtfirst
        tier: frontend
    spec:
      containers:
      - name: web
        image: mariodsasir/php-apache:twt
        imagePullPolicy: Always
        ports:
        - containerPort: 8081